"""OPS table definitions split out from app.database."""

from __future__ import annotations

from sqlalchemy import Boolean, Column, DateTime, Float, Integer, LargeBinary, MetaData, String, Table, Text


def register_ops_tables(metadata: MetaData) -> dict[str, Table]:
    ops_checklist_sets = Table(
        "ops_checklist_sets",
        metadata,
        Column("id", Integer, primary_key=True, autoincrement=True),
        Column("set_id", String(80), nullable=False, unique=True),
        Column("label", String(200), nullable=False),
        Column("task_type", String(80), nullable=False),
        Column("version_no", Integer, nullable=False, default=1),
        Column("lifecycle_state", String(20), nullable=False, default="active"),
        Column("source", String(40), nullable=False, default="catalog"),
        Column("created_at", DateTime(timezone=True), nullable=False),
        Column("updated_at", DateTime(timezone=True), nullable=False),
    )

    ops_checklist_set_items = Table(
        "ops_checklist_set_items",
        metadata,
        Column("id", Integer, primary_key=True, autoincrement=True),
        Column("set_id", String(80), nullable=False),
        Column("seq", Integer, nullable=False),
        Column("item_text", String(200), nullable=False),
        Column("created_at", DateTime(timezone=True), nullable=False),
        Column("updated_at", DateTime(timezone=True), nullable=False),
    )

    ops_checklist_set_revisions = Table(
        "ops_checklist_set_revisions",
        metadata,
        Column("id", Integer, primary_key=True, autoincrement=True),
        Column("set_id", String(80), nullable=False),
        Column("base_version_no", Integer, nullable=True),
        Column("proposed_version_no", Integer, nullable=False, default=1),
        Column("label", String(200), nullable=False),
        Column("task_type", String(80), nullable=False),
        Column("lifecycle_state", String(20), nullable=False, default="active"),
        Column("items_json", Text, nullable=False, default="[]"),
        Column("note", Text, nullable=False, default=""),
        Column("status", String(20), nullable=False, default="draft"),
        Column("created_by", String(80), nullable=False, default="system"),
        Column("submitted_by", String(80), nullable=True),
        Column("decided_by", String(80), nullable=True),
        Column("decision_note", Text, nullable=False, default=""),
        Column("created_at", DateTime(timezone=True), nullable=False),
        Column("updated_at", DateTime(timezone=True), nullable=False),
        Column("submitted_at", DateTime(timezone=True), nullable=True),
        Column("decided_at", DateTime(timezone=True), nullable=True),
        Column("applied_at", DateTime(timezone=True), nullable=True),
    )

    ops_equipment_assets = Table(
        "ops_equipment_assets",
        metadata,
        Column("id", Integer, primary_key=True, autoincrement=True),
        Column("equipment_key", String(400), nullable=False, unique=True),
        Column("equipment_name", String(200), nullable=False),
        Column("location_name", String(120), nullable=True),
        Column("lifecycle_state", String(20), nullable=False, default="active"),
        Column("source", String(40), nullable=False, default="catalog"),
        Column("created_at", DateTime(timezone=True), nullable=False),
        Column("updated_at", DateTime(timezone=True), nullable=False),
    )

    ops_qr_assets = Table(
        "ops_qr_assets",
        metadata,
        Column("id", Integer, primary_key=True, autoincrement=True),
        Column("qr_id", String(80), nullable=False, unique=True),
        Column("equipment_id", Integer, nullable=True),
        Column("equipment_snapshot", String(200), nullable=True),
        Column("equipment_location_snapshot", String(120), nullable=True),
        Column("default_item", String(200), nullable=True),
        Column("checklist_set_id", String(80), nullable=True),
        Column("lifecycle_state", String(20), nullable=False, default="active"),
        Column("source", String(40), nullable=False, default="catalog"),
        Column("created_at", DateTime(timezone=True), nullable=False),
        Column("updated_at", DateTime(timezone=True), nullable=False),
    )

    ops_qr_asset_revisions = Table(
        "ops_qr_asset_revisions",
        metadata,
        Column("id", Integer, primary_key=True, autoincrement=True),
        Column("qr_asset_id", Integer, nullable=True),
        Column("qr_id", String(80), nullable=False),
        Column("change_source", String(40), nullable=False, default="qr_asset_api"),
        Column("change_action", String(20), nullable=False, default="updated"),
        Column("change_note", Text, nullable=False, default=""),
        Column("before_json", Text, nullable=False, default="{}"),
        Column("after_json", Text, nullable=False, default="{}"),
        Column("quality_flags_json", Text, nullable=False, default="[]"),
        Column("created_by", String(80), nullable=False, default="system"),
        Column("created_at", DateTime(timezone=True), nullable=False),
    )

    inspections = Table(
        "inspections",
        metadata,
        Column("id", Integer, primary_key=True, autoincrement=True),
        Column("site", String(120), nullable=False),
        Column("location", String(120), nullable=False),
        Column("cycle", String(40), nullable=False),
        Column("inspector", String(80), nullable=False),
        Column("inspected_at", DateTime(timezone=True), nullable=False),
        Column("equipment_id", Integer, nullable=True),
        Column("qr_asset_id", Integer, nullable=True),
        Column("equipment_snapshot", String(200), nullable=True),
        Column("equipment_location_snapshot", String(120), nullable=True),
        Column("qr_id", String(80), nullable=True),
        Column("checklist_set_id", String(80), nullable=True),
        Column("checklist_version", String(80), nullable=True),
        Column("transformer_kva", Float, nullable=True),
        Column("voltage_r", Float, nullable=True),
        Column("voltage_s", Float, nullable=True),
        Column("voltage_t", Float, nullable=True),
        Column("current_r", Float, nullable=True),
        Column("current_s", Float, nullable=True),
        Column("current_t", Float, nullable=True),
        Column("winding_temp_c", Float, nullable=True),
        Column("grounding_ohm", Float, nullable=True),
        Column("insulation_mohm", Float, nullable=True),
        Column("notes", Text, nullable=False, default=""),
        Column("risk_level", String(20), nullable=False),
        Column("risk_flags", Text, nullable=False, default=""),
        Column("created_at", DateTime(timezone=True), nullable=False),
    )

    inspection_evidence_files = Table(
        "inspection_evidence_files",
        metadata,
        Column("id", Integer, primary_key=True, autoincrement=True),
        Column("inspection_id", Integer, nullable=False),
        Column("site", String(120), nullable=False),
        Column("file_name", String(255), nullable=False),
        Column("content_type", String(120), nullable=False, default="application/octet-stream"),
        Column("file_size", Integer, nullable=False, default=0),
        Column("file_bytes", LargeBinary, nullable=False),
        Column("storage_backend", String(20), nullable=False, default="db"),
        Column("storage_key", String(400), nullable=True),
        Column("sha256", String(64), nullable=True),
        Column("malware_scan_status", String(20), nullable=False, default="unknown"),
        Column("malware_scan_engine", String(80), nullable=True),
        Column("malware_scanned_at", DateTime(timezone=True), nullable=True),
        Column("note", Text, nullable=False, default=""),
        Column("uploaded_by", String(80), nullable=False, default="system"),
        Column("uploaded_at", DateTime(timezone=True), nullable=False),
    )

    work_orders = Table(
        "work_orders",
        metadata,
        Column("id", Integer, primary_key=True, autoincrement=True),
        Column("title", String(200), nullable=False),
        Column("description", Text, nullable=False, default=""),
        Column("site", String(120), nullable=False),
        Column("location", String(120), nullable=False),
        Column("priority", String(20), nullable=False, default="medium"),
        Column("status", String(20), nullable=False, default="open"),
        Column("assignee", String(80), nullable=True),
        Column("reporter", String(80), nullable=True),
        Column("inspection_id", Integer, nullable=True),
        Column("equipment_id", Integer, nullable=True),
        Column("qr_asset_id", Integer, nullable=True),
        Column("equipment_snapshot", String(200), nullable=True),
        Column("equipment_location_snapshot", String(120), nullable=True),
        Column("qr_id", String(80), nullable=True),
        Column("checklist_set_id", String(80), nullable=True),
        Column("due_at", DateTime(timezone=True), nullable=True),
        Column("acknowledged_at", DateTime(timezone=True), nullable=True),
        Column("completed_at", DateTime(timezone=True), nullable=True),
        Column("resolution_notes", Text, nullable=False, default=""),
        Column("is_escalated", Boolean, nullable=False, default=False),
        Column("created_at", DateTime(timezone=True), nullable=False),
        Column("updated_at", DateTime(timezone=True), nullable=False),
    )

    work_order_events = Table(
        "work_order_events",
        metadata,
        Column("id", Integer, primary_key=True, autoincrement=True),
        Column("work_order_id", Integer, nullable=False),
        Column("event_type", String(40), nullable=False),
        Column("actor_username", String(80), nullable=False, default="system"),
        Column("from_status", String(20), nullable=True),
        Column("to_status", String(20), nullable=True),
        Column("note", Text, nullable=False, default=""),
        Column("detail_json", Text, nullable=False, default="{}"),
        Column("created_at", DateTime(timezone=True), nullable=False),
    )

    workflow_locks = Table(
        "workflow_locks",
        metadata,
        Column("id", Integer, primary_key=True, autoincrement=True),
        Column("site", String(120), nullable=False),
        Column("workflow_key", String(120), nullable=False),
        Column("status", String(20), nullable=False, default="draft"),
        Column("content_json", Text, nullable=False, default="{}"),
        Column("requested_ticket", String(120), nullable=True),
        Column("last_comment", Text, nullable=False, default=""),
        Column("lock_reason", Text, nullable=True),
        Column("unlock_reason", Text, nullable=True),
        Column("created_by", String(80), nullable=False, default="system"),
        Column("updated_by", String(80), nullable=False, default="system"),
        Column("reviewed_by", String(80), nullable=True),
        Column("approved_by", String(80), nullable=True),
        Column("locked_by", String(80), nullable=True),
        Column("unlocked_by", String(80), nullable=True),
        Column("created_at", DateTime(timezone=True), nullable=False),
        Column("updated_at", DateTime(timezone=True), nullable=False),
        Column("reviewed_at", DateTime(timezone=True), nullable=True),
        Column("approved_at", DateTime(timezone=True), nullable=True),
        Column("locked_at", DateTime(timezone=True), nullable=True),
        Column("unlocked_at", DateTime(timezone=True), nullable=True),
    )

    return {
        "ops_checklist_sets": ops_checklist_sets,
        "ops_checklist_set_items": ops_checklist_set_items,
        "ops_checklist_set_revisions": ops_checklist_set_revisions,
        "ops_equipment_assets": ops_equipment_assets,
        "ops_qr_assets": ops_qr_assets,
        "ops_qr_asset_revisions": ops_qr_asset_revisions,
        "inspections": inspections,
        "inspection_evidence_files": inspection_evidence_files,
        "work_orders": work_orders,
        "work_order_events": work_order_events,
        "workflow_locks": workflow_locks,
    }
